### ISSUE TITLE
Application not starting when running Docker-compose up

### ISSUE THREAD

**Issue by adithyapatha** [mocktaillbird/mocktail.bird#1]
**Describe the bug**
Application throwing error when trying to start

**To Reproduce**
1. As a new User clone the project to my local
2. Goto project location in command terminal
3. Run docker-compose up
Below is the error:
**Setting up openjdk-11-jdk-headless:amd64 (11.0.3+1-1~bpo9+1) ...
Removing intermediate container c6798b9e20e9
 ---> 64a7920e48b5
Step 4/7 : WORKDIR /app
Removing intermediate container 57bde9572413
 ---> 309f7e0ee499
Step 5/7 : COPY ./service/target/mocktail-bird-service-*.jar  /app/
ERROR: Service 'app' failed to build: COPY failed: no source files were specified**
![image](https://user-images.githubusercontent.com/9124463/55517919-e4ddd500-5626-11e9-88b3-3a914f741abc.png)

**Comment by mocktaillbird** [comment]
please run mvn clean install and then run docker-compose up.
Appreciate for the test.
